training:
  batch_size: 8
  num_epochs: 100
  learning_rate: 1e-4
  weight_decay: 1e-6
  warmup_steps: 1000
  gradient_clip_norm: 1.0
  save_every_n_epochs: 10
  validate_every_n_epochs: 5
  
data:
  metadata_path: "/media/soykat/Data/Università/Computer Science/Deep Learning and Applied AI/project/DJNet-Diffusion/metadata.csv"
  data_root: "/media/soykat/Data/Università/Computer Science/Deep Learning and Applied AI/project/DJNet-Dataset/output/djnet_dataset_20k"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  num_workers: 4
  pin_memory: true
  shuffle: true

logging:
  log_dir: "logs"
  use_wandb: false
  wandb_project: "djnet-diffusion"
  log_every_n_steps: 100
  save_audio_samples: true
  num_audio_samples: 4

optimization:
  optimizer: "AdamW"
  scheduler: "cosine"
  min_lr: 1e-6

checkpointing:
  checkpoint_dir: "checkpoints"
  resume_from_checkpoint: null
  save_best_only: false
